fix bug on save
InseeFr/Stromae pull request #290
Opened 2023-04-27 06:30 UTC by renaud23

J'ai remis onChange dans les args de lunatic.
C'est elle qui permet de suivre les variables en évolution et de sauvegarder les changements.

2023-04-27 07:46 UTC, Grafikart requested changes
Je me demande si il ne faudrait pas faire un commit sur v3-develop en passant eslint/prettier sur tous les fichier pour éviter d'avoir des modifications parasite dans les PR.

Sinon ça semble bon pour moi

2023-04-27 07:46 UTC, Grafikart commented on src/components/orchestrator/Orchestrator.tsx
> + */
JSDoc inutile ici

2023-04-27 07:46 UTC, Grafikart commented on src/components/orchestrator/Saving/SaveOnPage.tsx
> +				const somethingToSave = await save();
Pas besoin d'avoir une fonction dans une fonction 

```js
useCallback(async() =>
```

Fonctionne

2023-04-27 08:29 UTC, renaud23 commented on src/components/orchestrator/Saving/SaveOnPage.tsx
> +				const somethingToSave = await save();
changé dans une autre PR (à l'instant)

2023-04-27 08:31 UTC, renaud23 commented on src/components/orchestrator/Orchestrator.tsx
> + */
on pourrais peut-être envisager un truc comme husky

2023-05-03 08:34 UTC, Grafikart approved these changes

2023-05-03 09:05 UTC, merged