new lunatic-dsfr accordion component
InseeFr/Stromae pull request #329
Opened 2023-07-10 09:12 UTC by aymendebbabi1989

2023-07-13 16:51 UTC, isMattCoding commented
Since the AccordionDSFR component has a button in it, it cannot be used inside a <form> element because it causes the form to be submitted.  Therefore I created a new component to call ComponentsRenderer inside a div, and not a form.

2023-07-17 15:40 UTC, Grafikart commented on src/components/ComponentsRenderer/ComponentsRenderer.tsx
> +	}, [getComponents, except, only]);
Je ne suis pas sûr de l'utilité du state ici. Pourquoi ne pas dériver directement.

```ts
const components = getComponents?.().filter(....)
```

2023-07-17 15:42 UTC, Grafikart commented on src/components/whyThisQuestion/WhyThisQuestion.tsx
Remplaçable par le ComponentsRenderer non ?

2023-07-18 09:23 UTC, isMattCoding commented on src/components/whyThisQuestion/WhyThisQuestion.tsx
Autant pour moi, c'est remplacé par `ComplementaryComponents` et `ComponentRenderer`.

2023-07-18 09:23 UTC, isMattCoding commented on src/components/whyThisQuestion/WhyThisQuestion.tsx
> +	}, [getComponents]);
remplacé par `ComplementaryComponents` et `ComponentRenderer`.

2023-07-18 09:24 UTC, isMattCoding commented on src/components/whyThisQuestion/WhyThisQuestion.tsx
> +				if (componentType in lunatic && componentType === 'QuestionExplication') {
remplacé par `ComplementaryComponents` et `ComponentRenderer`.

2023-07-26 08:27 UTC, Grafikart commented
Pour ajouter du contexte.

## Problème

Avec l'introduction du composant QuestionExplication du DSFR on souhaite afficher certains composant en fin de formulaire.

L'objectif de cette MR est d'isolé le composant QuestionExplication pour l'afficher en bas de page plutôt que dans le formulaire

2023-07-26 08:58 UTC, Grafikart requested changes
Mis à part le point sur continuer le reste est ok pour moi

2023-07-26 08:58 UTC, Grafikart commented on src/components/navigation/Continuer.tsx
> +      nativeButtonProps={{"form": `stromae-form${(except && except[0]) ? `-except-${except.join('-').toLowerCase()}` : ``}`, "type": "submit", "aria-atomic": true, "aria-disabled": waiting}}
Je ne comprends pas trop le besoin d'ajouter le except ici

2023-08-04 09:17 UTC, isMattCoding approved these changes
LGTM !

2023-08-04 09:19 UTC, isMattCoding commented on src/components/navigation/Continuer.tsx
> +      nativeButtonProps={{"form": `stromae-form${(except && except[0]) ? `-except-${except.join('-').toLowerCase()}` : ``}`, "type": "submit", "aria-atomic": true, "aria-disabled": waiting}}
J'ai ajouté ça parce qu'au début on a prévu d'utiliser deux `<Formulaire />`, donc il fallait avoir des ids uniques. Maintenant ce n'est plus nécessaire donc c'est bon que c'est supprimé 😄

2023-08-04 09:42 UTC, Grafikart approved these changes

2023-08-04 12:54 UTC, merged