Feat/v3 state data.state
InseeFr/Stromae pull request #351
Opened 2023-08-09 10:10 UTC by renaud23

prise en compte et évolution de stateData.state
- INIT : valeur inital pour Stromae, envoyé par l'API, lorsque le document est vierge. pas vraiment pris en compte par stromae
- COLLECTED : dés qu'une variable bouge sur le questionnaire
- VALIDATED : transmis lorsque l'utilisateur clique et sauvegarde sur la dernière page du questionnaire.

Si l'utilisateur est en etat VALIDATED, il sera redirigé vers la page postSubmit et ne pourra pas modifier une variable depuis le questionnaire

2023-08-11 10:05 UTC, isMattCoding commented
> Il faudrait rebase car je vois trop de fichiers modifié ici

J'ai fait une rebase, normalement tu peux continuer le review 🙏

2023-08-11 13:50 UTC, Grafikart requested changes

2023-08-11 13:50 UTC, Grafikart commented on src/components/RedirectIfValidated/RedirectIfValidated.tsx
> +}
Pourquoi faire un composant? Cela devrait plutôt être un hook avec la logique placée directement dans l'orchestrator non ?

2023-08-11 13:50 UTC, Grafikart commented on src/components/loadSourceData/LoadFromApi.tsx
> +						await surveyApi.putSurveyUnitStateData(state, unit, accessToken);
Double condition peut être fusionné

2023-08-11 13:50 UTC, Grafikart commented on src/components/orchestrator/Saving/useSaving.ts
>  export function useSaving(args: SavingArgs) {
Commenter l'objectif de ce hook, si il renvoie un booléen on préfèrera le nommer useIsSaving()

2023-08-11 13:50 UTC, Grafikart commented on src/typeStromae/type.ts
> +	state?: string | null;
On ne peut pas mettre un enum là du coup plutôt que le commentaire?

2023-08-11 13:50 UTC, Grafikart commented on src/typeStromae/type.ts
> +	// dernière page sauvegardé, obtenu par l'API (!= de pageTag)
Commentaire à passer en Anglais

2023-08-11 13:50 UTC, Grafikart commented on src/typeStromae/type.ts
> +	// etat du questionnaire fournit par l'API ('INIT' | 'COLLECTED' | 'VALIDATED')
Commentaire à passer en Anglais

2023-08-11 14:34 UTC, renaud23 commented on src/typeStromae/type.ts
> +	state?: string | null;
oui et j'en ai déjà crée une.

2023-09-01 09:37 UTC, Grafikart approved these changes

2023-09-07 06:19 UTC, merged