Fix/v3 save on next page
InseeFr/Stromae pull request #385
Opened 2023-09-08 08:43 UTC by renaud23

Jusqu'alors, currentPage, sauvegardé par l'API contenait la page sur laquelle on étatit lorsque l'on cliquait sur le bouton continuer ou précédent. Désormais, currentPage contient la page sur laquelle on arrive après avoir pressé un bouton de navigation.
- currentPage transmis au démarrage par getStateData est transmis dans à la modal ContinueOrRestart dans pageFromAPI
- currentPage contient maintenant la valeur pager.page, transmis à l'API

2023-09-08 10:04 UTC, Grafikart requested changes
Il y a des problème de clarté dans le code, donc des petites modifications sont nécessaires.

2023-09-08 10:04 UTC, Grafikart commented on src/components/orchestrator/UseLunatic.tsx
> +
Si currentPage est dérivé depuis le pager autant ne pas utiliser d'état

```
const currentPage = pager.page
```

2023-09-08 10:04 UTC, Grafikart commented on src/typeStromae/type.ts
> +	// Page give by API.getSuData at launch
"given"

2023-09-11 06:46 UTC, renaud23 commented on src/components/orchestrator/Saving/SaveOnPage.tsx
>  	} = rest;
rest permet d'isoler children et de ne pas le transmettre en dessous

2023-09-11 06:55 UTC, renaud23 commented on src/components/orchestrator/Saving/SaveOnPage.tsx
> +			previousPage !== currentPage
TS m'embête avec eslint(@shopify/binary-assignment-parens). Quand j'essaie de faire comme ça, il m'oblige à mettre des parenthèses, retirées immédiatement par prettier :(

2023-09-11 06:58 UTC, renaud23 commented on src/components/orchestrator/Saving/SaveOnPage.tsx
> +			(async () => {
d'autant plus qu'on a déjà écrit le hook dans stromae

2023-09-11 07:12 UTC, renaud23 commented on src/components/orchestrator/UseLunatic.tsx
> +
oki. je change.

2023-09-11 07:14 UTC, renaud23 commented on src/components/orchestrator/Saving/SaveOnPage.tsx
> +	const onSave = useRef(false);
ce sera shouldSync

2023-09-11 14:56 UTC, Grafikart commented on src/components/orchestrator/Saving/SaveOnPage.tsx
> +			{...props}
Vu que tu passe props qui contient childrent tu n'as pas forcément besoin  de passer l'enfant après 


```jsx

		<CloneElements<OrchestratedElement>
			{...props}
			goNextPage={handleNextPage}
			goPreviousPage={handleGoBack}
			savingFailure={savingFailure}
			waiting={waiting}
		/>
```

2023-09-11 14:59 UTC, merged