Feat/v3 redirection 301
InseeFr/Stromae pull request #407
Opened 2023-09-21 12:02 UTC by isMattCoding

When receiving an error 301, we need to be able to customise the error message using metadata. 

Solution: 
Add another navigate function in LoadSourceData to handle the 301 response.  This function redirects to either `/301` by default or `/questionnaire/${SURVEY_NAME}/301` if there is a survey present. 

To avoid creating another Error component, I refactorised the component used for 404 so that it can handle the code 301. 

In order to access the customisable content in the metadata file, we wrap the error component with LoadFromApi similarly to the Optional.tsx component.

2023-09-22 08:08 UTC, Grafikart requested changes

2023-09-22 08:08 UTC, Grafikart commented on src/pages/error/html/ErrorPage.tsx
> +	}, [metadata]);
Pas de setter à la racine d'un useEffect

```js
const content = metadata?.errrPage
```

2023-09-22 08:08 UTC, Grafikart commented on src/pages/error/html/ErrorPage.tsx
> +			: 'Si vous avez tapé l’adresse web dans le navigateur, vérifiez qu’elle est correcte. La page n’est peut-être plus disponible. Dans ce cas, pour continuer votre visite vous pouvez retourner sur la
Pas idéal ces conditions à répétition, peut être créer une fonction en dehors du composant

```js
const {title, subtitle, paragraph} = getTextFor(code, content)
```

2023-09-22 08:11 UTC, laurentC35 reviewed
I'm not sure about 301 / 302 code.

2023-09-22 08:11 UTC, laurentC35 commented on mock-api/api/survey-unit/kqhlz2/GET.js
> +		response.statusCode = 302;
You PR is about 301 code, you have `302` here.

Do you have a test in your mock-api for the `301` code.

2023-09-22 08:41 UTC, isMattCoding commented
> I'm not sure about 301 / 302 code.

Initially, I thought we needed to treat 302 errors, but I realised when I connected to the api that it's actually a 301 error. 😓

2023-09-25 08:09 UTC, Grafikart requested changes
Quelques changements à faire

2023-09-25 08:09 UTC, Grafikart commented on src/components/orchestrator/LoadSourceData.tsx
> +		}
Je pense que tu pourrais simplifier la condition, la destructuration te fait rajouter une ligne pas vraiment utile

```jsx
if (data?.status === 301) {
    navigate(uri301(survey, data.message)
} else {
	navigate(uri404());
}
```

2023-09-25 08:09 UTC, Grafikart commented on src/lib/domainUri/uri.ts
> +export function uri301(survey?: string, message?: string) {
Ajouter ici un petit commentaire pour expliquer le rôle de la fonction (contexte)

2023-09-25 08:09 UTC, Grafikart commented on src/pages/error/Error.tsx
> +export function ErrorRedirection({ code }: { code?: number }) {
Je trouve le nom bizarre vu que ça gère aussi les erreurs 404, tu peux laisser RouteError je pense, ou renommer PageError à la limite (pour éviter de prendre le mot clef Error de JavaScript

2023-09-25 08:09 UTC, Grafikart commented on src/pages/error/html/ErrorPage.tsx
> +		return { title, subtitle, paragraph };
tu peux

```js 
return {
title: '....',
subtitle: '...',
paragraph: '....'
}
```

Pas forcément besoin d'introduire des variables intermédiaire, pareil au dessus

2023-09-25 08:09 UTC, Grafikart commented on src/pages/error/html/ErrorPage.tsx
> +	}, [metadata]);
Pas de bénéfice à mémoiser cela je pense.

2023-09-25 08:09 UTC, Grafikart commented on src/pages/error/html/ErrorPage.tsx
> +	useEffect(() => {}, [metadata]);
Ne sert à rien

2023-09-25 08:09 UTC, Grafikart commented on src/pages/error/html/ErrorPage.tsx
> +	}, [getMetadata]);
Dans ce genre de situation ne pas hésiter à utiliser la syntaxe callback des promesses qui est plus simple dans certains cas.

```js
useEffect(() => {
    getMetadata().then(setMetadata)
})
```

2023-09-25 09:47 UTC, laurentC35 commented on mock-api/api/questionnaire/recensement/metadata/parametres.json
> +	"redirections": { "302": "/recensement/commune-kput" },
Still `302` code

2023-09-25 09:50 UTC, Grafikart approved these changes

2023-09-25 09:50 UTC, Grafikart commented on src/pages/error/html/ErrorPage.tsx
> +	if (code && code === 301 && errorType) {
if (code === 301 suffit pas ? le code && code === 301 semble redondant.

2023-09-25 11:15 UTC, laurentC35 approved these changes

2023-09-25 14:55 UTC, merged