Fix/v3 validated status
InseeFr/Stromae pull request #416
Opened 2023-09-26 13:29 UTC by renaud23

Le statut doit passer à validated lorsque l'on quitte la dernière page pour rejoindre la page de post collecte.

2023-09-27 17:05 UTC, Grafikart requested changes
Le code me semble complexe et assez difficile à comprendre pour une nouvelle personne.
Peut être que ma compréhension du problème n'est pas complète (description du problème un peu court).

Aussi, quitte à repasser sur des fichier, il faudrait essayer de les renommer plus correctement.

- Un composant qui s'appel `UseLunatic` que l'on confond avec `useLunatic` 
- Des composants nommé avec des verbes "save" qui font penser à des actions.

2023-09-27 17:05 UTC, Grafikart commented on src/components/orchestrator/Saving/useSaving.ts
> + * le statut à COMPLETED. Le statut isLastPage est résolu au moment où on appel la fonction et lui est transmis par un paramètre.
Je ne comprends pas cette remarque, si on veut sauvegarder la contenu de la page précédente on peut imaginer sauvegarder les données qui sont nécessaire dans une ref (qui n'est mis à jour qu'au prochain changement de pageTag

2023-09-28 06:54 UTC, renaud23 commented on src/components/orchestrator/Saving/SaveOnSequence.tsx
> +						const somethingToSave = await save(isLastPage ?? false);
Propose moi un nom stp et je ferais le changement.

2023-09-28 07:16 UTC, renaud23 commented on src/components/orchestrator/Saving/SaveOnSequence.tsx
> +						const somethingToSave = await save(isLastPage ?? false);
ça devait être un useEffect qui pouvait se coller direct dans la fonction de rappel

2023-09-28 07:20 UTC, renaud23 commented on src/components/orchestrator/Saving/SaveOnPage.tsx
> +		makeSave(false);
saving status aurait été plus à propos

2023-09-28 07:23 UTC, renaud23 commented on src/components/orchestrator/Saving/SaveOnPage.tsx
> +	}, [goNextPage, shouldSync, isLastPage, makeSave]);
Il s'agit de sauvegarder lorsque l'on quitte cette page. Si j'écoute pageTag (ce que j'ai fait au début), on n'ai déjà plus dans la page quand il faut rappeler la fonction de sauvegarde. La difficulté vient du fait qu'on sauvegarde toujours après que lunatic est fini de tourner les pages.

2023-09-28 07:26 UTC, renaud23 commented on src/components/orchestrator/Saving/SaveOnPage.tsx
> +	}, [goNextPage, shouldSync, isLastPage, makeSave]);
L'autre manière c'est d'appeler la sauvegarde sur la page de post collecte. ça oblige juste à étaler un peu la logique de sauvegarde.

2023-09-28 13:46 UTC, Grafikart approved these changes

2023-09-28 14:56 UTC, laurentC35 approved these changes

2023-09-28 15:08 UTC, merged